[project]
name = "playpen_dspy"
version = "0.1.0"
description = "Add a short description here"
authors = ["Katherine Rosenfeld <krosenf@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
dspy-ai = ">=2.4.9,<2.5"
